### ISSUE TITLE
Canvas - insertion of math equations gives pager error (latex related?)

### ISSUE THREAD

**Issue by JedMeister** [turnkeylinux/tracker#1103]
As reported via support, our v14.2 Canvas appliance does not appear to support insertion of math equations?!

Hopefully we'll develop a workaround ASAP and include the fix by default for v15.0.

**Comment by JedMeister** [comment]
Workaround developed by @qq7:

What you need to do is to go to /var/www/canvas/config  and run `cp dynamic_settings.yml.example dynamic_settings.yml`

Then, in the newly created `dynamic_settings.yml`, add a section called production, so it looks this way:
```
production:
  canvas:
    encryption-secret: "astringthatisactually32byteslong"
    signing-secret: "astringthatisactually32byteslong"
  rich-content-service:
    app-host: "rce.docker"
development:
  address-book:
    app-host: "http://address-book.docker"
    secret: "opensesame"
... so on
```

Except you should change both encryption-secret and signing-secret to a long obfuscated string, which can be generated by running `echo $(mcookie)$(mcookie)$(mcookie)` in the command line. 

----

When we implement this into the Canvas appliance, we'll need to update/re-generate the secret strings on firstboot, via an `overlay/usr/lib/inithooks/firstboot.d/20regen-canvas-secrets` file (or make it 21 or 22 if it needs to run after the `20regen-rails-secrets`).
