### ISSUE TITLE
Redmine email notifications not sending

### ISSUE THREAD

**Issue by alonswartz** [turnkeylinux/tracker#12]
Reported on [lp#1051409](https://bugs.launchpad.net/turnkeylinux/+bug/1051409) by @JedMeister on 2012-09-15
#### Description

Bug reported and fix provided by TS in the forums (http://www.turnkeylinux.org/forum/support/20120915/redmine-email-notification-fix-solved)

Running Redmine 12.0.1 on Proxmox VE 2.1.14, Postfix email notifications did not work for me out of the box.

debian-6-turnkey-redmine_12.0.1_i386
/var/www/redmine/config/configuration.yml

Original:

```
production:
 email_delivery:
   delivery_method: :smtp
   smtp_settings:
     address: "localhost"
     port: 25
```

Changed to:

```
production:
 email_delivery:
   delivery_method: :sendmail
   smtp_settings:
     address: 127.0.0.1
     port: 25
```

Now working. Reference post at redmine.org http://www.redmine.org/boards/2/topics/6641
