### ISSUE TITLE
Gitlab: An unexpected error occurred (redis-cli returned 1)

### ISSUE THREAD

**Issue by jstruebel** [turnkeylinux/tracker#519]
I was getting the error "Gitlab: An unexpected error occurred (redis-cli returned 1)" when pushing to a fresh gitlab install. Based on the information in http://geekwerks.ca/2014/10/05/fixing-gitlab-redis-connection.html. I modified the redis settings in `/home/git/gitlab-shell/config.yml` and that fixed the issue.

The original settings were:

```
# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  # host: 127.0.0.1
  # port: 6379
  # pass: redispass # Allows you to specify the password for Redis
  database: 0
  socket: /var/run/redis/redis.sock # Comment out this line if you want to use TCP
  namespace: resque:gitlab
```

The correct settings are:

```
# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  # pass: redispass # Allows you to specify the password for Redis
  database: 0
  # socket: /var/run/redis/redis.sock # Comment out this line if you want to use TCP
  namespace: resque:gitlab
```
