### ISSUE TITLE
Please support user-data on OpenStack / console password output broken

### ISSUE THREAD

**Issue by vondrt4** [turnkeylinux/tracker#594]
Hi!
I have a use-case where I would like to use Turnkey Linux on OpenStack without setting SSH keys. 

Looking at https://www.turnkeylinux.org/docs/inithooks, the image should output a random password in the console log, yet the log only contains kernel output.

Secondly, it says that I can configure the root password with a config file in /etc/inithooks.conf. Injecting the file as per http://docs.openstack.org/openstack-ops/content/instances.html (see the end) did not work on my OpenStack. I see an empty file when I log in (I had the key just in case).

The image does read the OpenStack metadata service to get the key. Why not have it read the user data and dump it to the inithooks.conf file?

Or support full cloud-init in the image. For bare OS images, we use scripts such as (see below) to set the password. It also handles resizing the image to match flavor size, which you currently do not have.
```
#cloud-config
ssh_pwauth: True
users:
  - name: user
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock-passwd: false
    passwd: password
```
